#!/bin/bash

function showBanner {
  echo '   ______              __    __        ___       '
  echo '   \  __ \____ _____  / /_  / /_____ _/ (_)___ _ '
  echo '   / /_/ / __ `/ __ \/ __ \/ __/ __ `/ / / __ `/ '
  echo '  / _, _/ /_/ / /_/ / / / / /_/ /_/ / / / /_/ /  '
  echo ' /_/ |_|\__,_/ .___/_/ /_/\__/\__,_/_/_/\__,_/   '
  echo '            /_/                                  '
  echo '                                                 '
}

function showHelp {
  showBanner
  echo "Help text has not been written yet"
}

function init {
  echo "node version:"
  node -v
}

# Entry point
case "$1" in
help)
  showHelp
  ;;
init)
  init
  ;;
*)
  echo "Unknown command $1"
  exit 1
  ;;
esac
